// priority: 1000
ServerEvents.recipes(event => {
    // event.remove({ mod: 'dimpaintings'})
    // event.remove({ mod: 'waystones'})
    // event.remove({ mod: 'arcanelanterns'})
})

ServerEvents.recipes(event => {
    event.remove({ output: 'sophisticatedbackpacks:iron_backpack' })
    event.remove({ output: 'sophisticatedbackpacks:gold_backpack' })
    event.remove({ output: 'sophisticatedbackpacks:netherite_backpack' })
    event.remove({ output: 'sophisticatedbackpacks:backpack' })
    event.remove({ output: 'sophisticatedbackpacks:copper_backpack' })
    event.remove({ output: 'sophisticatedbackpacks:diamond_backpack' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_4' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_3' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_2' })
    event.remove({ output: 'sophisticatedbackpacks:upgrade_base' })
    event.remove({ output: 'sophisticatedbackpacks:anvil_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:auto_blasting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:tank_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:auto_smoking_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:inception_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_magnet_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:magnet_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_compacting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_void_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:void_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:deposit_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_restock_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:restock_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:refill_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_deposit_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_refill_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_1' })
    event.remove({ output: 'sophisticatedbackpacks:everlasting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:smelting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:blasting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:smoking_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:auto_smelting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:stonecutter_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:crafting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_starter_tier' })
    event.remove({ output: 'sophisticatedbackpacks:xp_pump_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_pump_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:pump_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:battery_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_tool_swapper_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:tool_swapper_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:pickup_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_filter_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:filter_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_pickup_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_feeding_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:feeding_upgrade' })
})