const { OVERLIMIT, COMMON, RARE, EPIC, LEGENDARY } = require("../../utils/itemborder")

StartupEvents.registry('item', event => {
    // 和平之戒
    // todo 补充材质
    event.create('peaceful_ring')
        .maxStackSize(1)
        .rarity('epic')
        .tag(EPIC)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip(() => true)
        )
        .texture('kubejs:item/curios/peaceful_ring')

    // 窃听之戒
    event.create('snoop_ring')
        .maxStackSize(1)
        .rarity('epic')
        .tag(EPIC)
        .tag('curios:ring')
        .tag('kubejs:snoop')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:decode_ability', 'SnoopRingDecodeAbility', 3, 'addition')
        )
        .texture('kubejs:item/curios/snoop_ring')

    // 月见草之语
    event.create('evening_primrose_ring')
        .maxStackSize(1)
        .tag('curios:ring')
        .tag(OVERLIMIT)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:encode_ability', 'EveningPrimroseEncodeAbility', -10, 'addition')
            .modifyAttribute('puffish_attributes:player.fortune', 'EveningPrimroseFortune', 1, 'addition')
            .modifyAttribute('kubejs:treasure_fortune', 'EveningPrimroseTreasureFortune', 4, 'addition')
            .modifyAttribute('kubejs:treasure_distance', 'EveningPrimroseTreasureDistance', 500, 'addition')
        )
        .texture('kubejs:item/curios/evening_primrose_ring')

    // 红宝石戒指
    event.create('common_ruby_ring')
        .maxStackSize(1)
        .rarity('common')
        .tag(COMMON)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:treasure_fortune', 'RubyRingTreasureFortune', 1, 'addition')
        )
        .texture('kubejs:item/curios/ruby_ring')

    event.create('rare_ruby_ring')
        .maxStackSize(1)
        .rarity('rare')
        .tag(RARE)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:treasure_fortune', 'RubyRingTreasureFortune', 1.5, 'addition')
        )
        .texture('kubejs:item/curios/ruby_ring')

    event.create('epic_ruby_ring')
        .maxStackSize(1)
        .rarity('epic')
        .tag(EPIC)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('miapi:generic.crit_chance', 'RubyRingCritChance', 0.05, 'addition')
            .modifyAttribute('kubejs:treasure_fortune', 'RubyRingTreasureFortune', 2, 'addition')
        )
        .texture('kubejs:item/curios/ruby_ring')

    event.create('legendary_ruby_ring')
        .maxStackSize(1)
        .tag(LEGENDARY)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('miapi:generic.crit_chance', 'RubyRingCritChance', 0.08, 'addition')
            .modifyAttribute('kubejs:treasure_fortune', 'RubyRingTreasureFortune', 3, 'addition')
        )
        .texture('kubejs:item/curios/ruby_ring')

    // 蓝宝石戒指
    event.create('common_sapphire_ring')
        .maxStackSize(1)
        .rarity('common')
        .tag(COMMON)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:decode_ability', 'SapphireRingDecodeAbility', 2, 'addition')
        )
        .texture('kubejs:item/curios/sapphire_ring')

    event.create('rare_sapphire_ring')
        .maxStackSize(1)
        .rarity('rare')
        .tag(RARE)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:decode_ability', 'SapphireRingDecodeAbility', 4, 'addition')
        )
        .texture('kubejs:item/curios/sapphire_ring')

    event.create('epic_sapphire_ring')
        .maxStackSize(1)
        .rarity('epic')
        .tag(EPIC)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('minecraft:generic.max_health', 'SapphireRingMaxHealth', 2, 'addition')
            .modifyAttribute('kubejs:decode_ability', 'SapphireRingDecodeAbility', 6, 'addition')
        )
        .texture('kubejs:item/curios/sapphire_ring')

    event.create('legendary_sapphire_ring')
        .maxStackSize(1)
        .tag(LEGENDARY)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('minecraft:generic.max_health', 'SapphireRingMaxHealth', 4, 'addition')
            .modifyAttribute('kubejs:decode_ability', 'SapphireRingDecodeAbility', 8, 'addition')
        )
        .texture('kubejs:item/curios/sapphire_ring')
})