// priority: 500
const { ColonyCraftRecipes } = require("../../model/citizen_recipes_model")

ServerEvents.recipes(event => {
    event.remove({ output: 'sophisticatedbackpacks:upgrade_base' })

    event.remove({ output: 'sophisticatedbackpacks:anvil_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:auto_blasting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:tank_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:auto_smoking_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:inception_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:magnet_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:void_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:deposit_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:restock_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:refill_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:everlasting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:smelting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:blasting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:smoking_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:auto_smelting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:stonecutter_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:crafting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_starter_tier' })
    event.remove({ output: 'sophisticatedbackpacks:xp_pump_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:pump_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:battery_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:tool_swapper_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:pickup_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:filter_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:feeding_upgrade' })

    event.remove({ output: 'sophisticatedbackpacks:advanced_magnet_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_pickup_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_feeding_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_filter_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_tool_swapper_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_pump_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_deposit_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_refill_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_restock_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_compacting_upgrade' })
    event.remove({ output: 'sophisticatedbackpacks:advanced_void_upgrade' })

    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_4' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_3' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_2' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_1' })
})

ServerEvents.highPriorityData(event => {
    // 升级模板
    event.addJson(`kubejs:crafterrecipes/blacksmith/upgrade_base.json`,
        new ColonyCraftRecipes('blacksmith_crafting', Item.of('sophisticatedbackpacks:upgrade_base'), [Item.of('minecraft:iron_ingot', 4), Item.of('minecraft:gold_ingot', 4), Item.of('minecraft:crafting_table')])
            .setResearchId('kubejs:effects/usefulbackpackupgrade', true))

    // 基础升级
    event.addJson(`kubejs:crafterrecipes/lumberjack/anvil_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:anvil_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/auto_blasting_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:auto_blasting_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/tank_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:tank_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/auto_smoking_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:auto_smoking_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/inception_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:inception_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/magnet_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:magnet_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/void_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:void_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/deposit_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:deposit_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/restock_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:restock_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/refill_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:refill_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/everlasting_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:everlasting_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/smelting_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:smelting_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/blasting_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:blasting_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/smoking_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:smoking_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/auto_smelting_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:auto_smelting_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/stonecutter_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:stonecutter_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/crafting_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:crafting_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/stack_upgrade_starter_tier.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:stack_upgrade_starter_tier'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/xp_pump_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:xp_pump_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/pump_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:pump_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/battery_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:battery_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/tool_swapper_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:tool_swapper_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/pickup_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:pickup_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/filter_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:filter_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/feeding_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:feeding_upgrade'), [Item.of('sophisticatedbackpacks:upgrade_base')]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))

    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_magnet_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_magnet_upgrade'), [Item.of('sophisticatedbackpacks:magnet_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_pickup_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_pickup_upgrade'), [Item.of('sophisticatedbackpacks:pickup_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_feeding_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_feeding_upgrade'), [Item.of('sophisticatedbackpacks:feeding_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_filter_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_filter_upgrade'), [Item.of('sophisticatedbackpacks:filter_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_tool_swapper_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_tool_swapper_upgrade'), [Item.of('sophisticatedbackpacks:tool_swapper_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_pump_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_pump_upgrade'), [Item.of('sophisticatedbackpacks:pump_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_deposit_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_deposit_upgrade'), [Item.of('sophisticatedbackpacks:deposit_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_refill_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_refill_upgrade'), [Item.of('sophisticatedbackpacks:refill_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_restock_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_restock_upgrade'), [Item.of('sophisticatedbackpacks:restock_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_compacting_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_compacting_upgrade'), [Item.of('sophisticatedbackpacks:compacting_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/advanced_void_upgrade.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:advanced_void_upgrade'), [Item.of('sophisticatedbackpacks:void_upgrade'), Item.of('minecraft:diamond', 3)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))

    // 堆叠升级
    event.addJson(`kubejs:crafterrecipes/lumberjack/stack_upgrade_tier_1.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:stack_upgrade_tier_1'), [Item.of('sophisticatedbackpacks:upgrade_base'), Item.of('minecraft:netherite_ingot', 1)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/stack_upgrade_tier_2.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:stack_upgrade_tier_2'), [Item.of('sophisticatedbackpacks:stack_upgrade_tier_1', 4), Item.of('minecraft:netherite_ingot', 1)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/stack_upgrade_tier_3.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:stack_upgrade_tier_3'), [Item.of('sophisticatedbackpacks:stack_upgrade_tier_2', 4), Item.of('minecraft:netherite_ingot', 1)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
    event.addJson(`kubejs:crafterrecipes/lumberjack/stack_upgrade_tier_4.json`, new ColonyCraftRecipes('lumberjack_custom', Item.of('sophisticatedbackpacks:stack_upgrade_tier_4'), [Item.of('sophisticatedbackpacks:stack_upgrade_tier_3', 4), Item.of('minecraft:netherite_ingot', 1)]).setResearchId('kubejs:effects/usefulbackpackupgrade', true))
})