StartupEvents.registry('item', event => {
    event.create('newer_atlas')
        .maxStackSize(1)
        .maxDamage(3)
        .tag('curios:atlas')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:treasure_fortune', 'NewerAtlasTreasureFortune', 2, 'addition')
            .modifyAttribute('kubejs:treasure_distance', 'NewerAtlasTreasureDistance', 1000, 'addition')
            .modifyAttribute('kubejs:encode_ability', 'NewerAtlasEncodeAbility', 100, 'addition')
        )
        .texture('kubejs:item/curios/newer_atlas')

    event.create('common_atlas')
        .maxStackSize(1)
        .maxDamage(6)
        .tag('curios:atlas')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:treasure_distance', 'CommonAtlasTreasureDistance', 1000, 'addition')
            .modifyAttribute('kubejs:encode_ability', 'CommonAtlasEncodeAbility', 1, 'addition')
        )
        .texture('kubejs:item/curios/common_atlas')

    event.create('uncommon_atlas')
        .maxStackSize(1)
        .maxDamage(6)
        .tag('curios:atlas')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:treasure_distance', 'UncommonAtlasTreasureDistance', 1000, 'addition')
            .modifyAttribute('kubejs:encode_ability', 'UncommonAtlasEncodeAbility', 1, 'addition')
        )
        .texture('kubejs:item/curios/uncommon_atlas')

    event.create('wood_atlas')
        .maxStackSize(1)
        .maxDamage(6)
        .tag('curios:atlas')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:treasure_fortune', 'WoodAtlasTreasureFortune', 2, 'addition')
            .modifyAttribute('kubejs:treasure_distance', 'WoodAtlasTreasureDistance', 500, 'addition')
        )
        .texture('kubejs:item/curios/wood_atlas')
})
