StartupEvents.registry('item', event => {
    event.create('book_of_knowledge', 'basic')
        .maxStackSize(16)
        .texture('kubejs:item/book_of_knowledge')
    event.create('book_of_enlight', 'basic')
        .maxStackSize(16)
        .texture('kubejs:item/book_of_enlight')

    event.create('raid_book', 'basic')
        .maxStackSize(16)
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/raid_book')
    event.create('undead_raid_book', 'basic')
        .maxStackSize(16)
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/undead_raid_book')

    event.create('skill_book_strength')
        .maxStackSize(16)
        .texture('kubejs:item/skill_book_strength')
    event.create('skill_book_agility')
        .maxStackSize(16)
        .texture('kubejs:item/skill_book_agility')
    event.create('skill_book_intelligence')
        .maxStackSize(16)
        .texture('kubejs:item/skill_book_intelligence')


    event.create('teaching_manual_adaptability', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_adaptability')
    event.create('teaching_manual_agility', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_agility')
    event.create('teaching_manual_athletics', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_athletics')
    event.create('teaching_manual_creativity', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_creativity')
    event.create('teaching_manual_dexterity', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_dexterity')
    event.create('teaching_manual_focus', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_focus')
    event.create('teaching_manual_intelligence', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_intelligence')
    event.create('teaching_manual_knowledge', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_knowledge')
    event.create('teaching_manual_mana', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_mana')
    event.create('teaching_manual_strength', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_strength')
    event.create('teaching_manual_stamina', 'basic')
        .maxStackSize(16)
        .tag('kubejs:teaching_manual')
        .tag('minecolonies:hide_citizen_data')
        .texture('kubejs:item/teaching_manual_stamina')
})