StartupEvents.registry('item', event => {
    event.create('peaceful_ring')
        .maxStackSize(1)
        .tag('curios:ring')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip(() => true)
        )
        .texture('kubejs:item/curios/peaceful_ring')

    event.create('snoop_ring')
        .maxStackSize(1)
        .tag('curios:ring')
        .tag('kubejs:snoop')
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip((item, slotContext) => onlyPlayerCanEquip(item, slotContext))
            .modifyAttribute('kubejs:decode_ability', 'SnoopRingDecodeAbility', 3, 'addition')
        )
        .texture('kubejs:item/curios/snoop_ring')
})